# Generated by Django 4.2.7 on 2023-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note_user_alter_note_expire_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='expire_on',
            field=models.DateField(blank=True, db_index=True, default='', verbose_name='Expiry Date'),
        ),
    ]
