# Generated by Django 4.2.7 on 2023-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_note_updated_at_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='expire_on',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
