# Generated by Django 4.2.7 on 2023-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_note_updated_at_alter_note_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
